name: Semantic Versioning

on:
  push:
    branches:
      - master

jobs:
  workflow-calling:
    uses: Add-Jazztech/github-versioning-automation-workflow/.github/workflows/versioning_automation.yml@v1.0.0
    secrets: inherit
